apiVersion: v1
kind: Service
metadata:
  name: memberservice-service
spec:
  selector:
    app: memberservice
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memberservice-deployment
spec:
  selector:
    matchLabels:
      app: memberservice
  replicas: 1
  template:
    metadata:
      labels:
        app: memberservice
    spec:
      containers:
      - name: foodfile
        image: leonardkoll/foodfile:thesis
        ports:
        - containerPort: 80
        - containerPort: 443
        args:
        - "--mode=member"
        - "--elastic=http://localhost:9200/"
      - name: elasticsearch
        image: elasticsearch:7.5.0
        ports:
        - containerPort: 9200
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: es-volume
        env:
        - name: discovery.type
          value: single-node
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
      volumes:
      - name: es-volume
        emptyDir: {}