version: '3.7'

services:

    elasticsearch:
        image: elasticsearch:7.5.0
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        cap_add:
            - IPC_LOCK
        volumes:
            - esdata:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        environment:
            - discovery.type=single-node

    foodfile:
        build: ./
        command:
            - --mode=combined 
        ports:
            - 80:80
            - 443:443
        depends_on: 
            - elasticsearch

volumes:
    esdata:
        driver: local