version: '3.7'

services:

    elasticsearch:
        image: elasticsearch:7.5.0
        volumes:
            - esdata:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        environment:
            - discovery.type=single-node

    foodfile:
        build: ./
        ports:
            - 80:80
            - 443:443
        depends_on: 
            - elasticsearch

volumes:
    esdata:
        driver: local