version: '3.7'

services:

    elasticsearch:
        image: elasticsearch:7.5.0
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        cap_add:
            - IPC_LOCK
        volumes:
            - esdata:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        environment:
            - discovery.type=single-node

    foodfile:
        build: ./
#       image: leonardkoll/foodfile:latest
        command: --mode=regular
        ports:
            - 80:80
            - 443:443
        depends_on: 
            - elasticsearch
#       environment:
#           - ASPNETCORE_URLS=https://+;http://+
#           - ASPNETCORE_HTTPS_PORT=443
#           - ASPNETCORE_Kestrel__Certificates__Default__Password=
#           - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/foodfile.pfx
#       volumes:
#           - ./https:/https/

volumes:
    esdata:
        driver: local