version: '3.7'

services:

    elasticsearch:
        image: elasticsearch:7.5.0
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        cap_add:
            - IPC_LOCK
        volumes:
            - esdata:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        environment:
            - discovery.type=single-node

    freshfruitfarmers:
        build: ../FoodFile
        command: --this HOG6XJ --entityindex fffe --memberindex fffm --members "https://localhost:5001/api/members/" --salt fff
        ports:
            - 5002:80
        depends_on: 
            - elasticsearch
    
    sugarsilo:
        build: ../FoodFile
        command: --this 8XX99T --entityindex sse --memberindex ssm --members "https://localhost:5001/api/members/" --salt ss
        ports:
            - 5003:80
        depends_on: 
            - elasticsearch

volumes:
    esdata:
        driver: local